name: CI Pipeline
# To get trigger on every push in this repo in main branch
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  security-events: write
  packages: write
  actions: read

jobs:
  ci-pipeline-job:

    uses: sajjadathar/reusable-workflows/.github/workflows/ci-pipeline.yml@main
    with:
      run_codeql: true
      run_sonarqube: true
      run_build: true
      run_publish-ghcr: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  defploy-with-kubectl:
    needs: ci-pipeline-job
    runs-on: github-actions-scaleset-demo
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          kubectl version
          kubectl get nodes


