name: self-hosted-runner-demo
on:
  push:
    branches: 
      - dev

jobs:
  demo-1:
    name: Demo Job 1
    runs-on: github-actions-scaleset-demo # pick self-hosted runner with label "arc-demo"
    steps:
        - name: Display System Info
          run: |
            echo "Hostname: $(hostname)"
            echo "OS version: "
            lsb_release -a || cat /etc/os-release
            echo "Runner Name: ${{ runner.name }}"
            echo "Runner OS: ${{ runner.os }}"
            sleep 90 
  demo-2:
    name: Demo Job 2
    runs-on: github-actions-scaleset-demo
    steps:
        - name: Display System Info
          run: |
            echo "Hostname: $(hostname)"
            echo "OS version: "
            lsb_release -a || cat /etc/os-release
            echo "Runner Name: ${{ runner.name }}"
            echo "Runner OS: ${{ runner.os }}"
            sleep 90

            
    